#!/bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
[ ! -f ./dayplanner ] && echo "Please run me from the directory that contains the Day Planner executeable perl source file" && exit 1
! type xgettext &> /dev/null && echo "Please install xgettext before running me. It is usually included in the \"gettext\" package" && exit 1
echo -n "Building po/dayplanner.pot..."
# Get our current year
YEAR="`date +%Y`"
echo -n "."
# Create the pot-file
POTGEN="dayplanner_pot_gen_tmp_$$_$RANDOM_$YEAR.tmpdir"
if ! mkdir -p $POTGEN; then
       echo "Unable to create the $POTGEN directory!"
       exit 1
fi
cd $POTGEN
cp ../dayplanner .
cp ../dayplanner-notifier .
cp ../modules/DP-GeneralHelpers/lib/DP/GeneralHelpers.pm .
cp ../modules/DP-CoreModules/lib/DP/CoreModules.pm .
cp ../plugins/*pm .
cp ../modules/DP-iCalendar/lib/DP/iCalendar/WebExp.pm .
# This works around an damned annoying bug in xgettext when using --keyword=$i18n->get.
# Changing it to just gettext allows us to use the default, which isn't broken.
perl -pi -e 's#gettext\(\@\_\)#BUGBUGBUGBUGBUGBUGBUGBUGBUGBUGBUGBUGBUG#g; s#\$(this|self)->{i18n}->get(_advanced)?#gettext#g; s#({i18n}|\$(i18n|self))->get(_advanced)?#gettext#g;s#i18nwrapper(_advanced)?#gettext#g;' ./dayplanner ./dayplanner-notifier ./*.pm
echo -n "."
xgettext --copyright-holder 'Eskild Hustvedt' --msgid-bugs-address 'https://gna.org/bugs/?group=dayplanner' -o ../po/dayplanner.pot -d dayplanner --add-comments="TRANSLATORS" --language perl ./dayplanner ./dayplanner-notifier ./*.pm
cd ..
rm -rf $POTGEN
echo -n "."
# Fix the headers using perl
perl -pi -e "s%^# SOME DESCRIPTIVE TITLE.%# PO file for Day Planner%g;
s%^# This file is distributed under the same license as the PACKAGE package.%# This file is distributed under the GNU General Public License\\n# as published by the Free Software Foundation; either version 3 of the license\\n# or (at your option) any later version (the same license as Day Planner)\\n#%g;
s%^(#.+) YEAR %\$1 $YEAR %g" ./po/dayplanner.pot
echo -n "."
cd ..
echo " done."
