#!/bin/sh
[ ! -f ./dayplanner ] && echo "Please run me from the directory that contains the Day Planner executeable perl source file" && exit 1
! type xgettext &> /dev/null && echo "Please install xgettext before running me. It is usually included in the \"gettext\" package" && exit 1
echo -n "Building po/dayplanner.pot..."
# Get our current year
YEAR="`date +%Y`"
echo -n "."
# Create the pot-file
POTGEN="dayplanner_pot_gen_tmp_$$_$RANDOM_$YEAR.tmpdir"
if ! mkdir -p $POTGEN; then
       echo "Unable to create the $POTGEN directory!"
       exit 1
fi
cd $POTGEN
cp ../dayplanner .
cp ../dayplanner-notifier .
# This works around an damned annoying bug in xgettext when using --keyword=DP_gettext.
# Changing it to just gettext allows us to use the default, which isn't broken.
perl -pi -e 's#gettext\(\@\_\)#BUGBUGBUGBUGBUGBUGBUGBUGBUGBUGBUGBUGBUG#g;s#DP_gettext#gettext(#g' ./dayplanner ./dayplanner-notifier
echo -n "."
xgettext --copyright-holder 'Eskild Hustvedt' --msgid-bugs-address 'https://gna.org/bugs/?group=dayplanner' -o ../po/dayplanner.pot -d dayplanner --add-comments="TRANSLATORS" --language perl ./dayplanner ./dayplanner-notifier
cd ..
rm -rf $POTGEN
echo -n "."
# Fix the headers using perl
perl -pi -e "s%^# SOME DESCRIPTIVE TITLE.%# PO file for Day Planner%g;
s%^# This file is distributed under the same license as the PACKAGE package.%# This file is distributed under the GNU General Public License\\n# as published by the Free Software Foundation; either version 2 of the license\\n# or (at your option) any later version (the same license as Day Planner)\\n#%g;
s%^(#.+) YEAR %\$1 $YEAR %g" ./po/dayplanner.pot
echo -n "."
cd ..
echo " done."
