#!/usr/bin/perl
# postat
# Copyright (C) Eskild Hustvedt 2006
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

use strict;
use warnings;

sub InPath ($) {
	foreach (split /:/, $ENV{PATH}) { if (-x "$_/@_" and ! -d "$_/@_" ) {   return 1; } } return 0;
}

unless(-d "./po" and -e "./devel-tools/buildpot") {
	die("Please run me from the base of the day planner source tree (not the devel-tools/ dir)\n");
}

die("Pease install msgfmt before running me (usually included in the \"gettext\" package)\n") unless InPath("msgfmt");

system("perl ./devel-tools/updatepo");

print "\nStatistics:\n";
chdir("./po/");
foreach(<*.po>) {
	print "$_: ";
	system("LC_ALL=C msgfmt --statistics $_");
}
unlink("messages.mo");
