#!/usr/bin/perl
# updatepo
# Copyright (C) Eskild Hustvedt 2006
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;
use Fatal;

sub InPath ($) {
	foreach (split /:/, $ENV{PATH}) { if (-x "$_/@_" and ! -d "$_/@_" ) {   return 1; } } return 0;
}
sub SetLocale {
	foreach(keys(%ENV)) {
		next unless /^(LC|LANG)/;
		$ENV{$_} = $_[0];
	}
	$ENV{LC_ALL} = $_[0];
}

SetLocale("C");

unless(-d "./po" and -e "./devel-tools/buildpot") {
	die("Please run me from the base of the Day Planner source tree (not the devel-tools/ dir)\n");
}

die("Pease install msgmerge before running me (usually included in the \"gettext\" package)\n") unless InPath("msgmerge");

system("bash ./devel-tools/buildpot");
chdir("./po");
foreach(<*.po>) {
	print "Updating po/$_";
	system("msgmerge -U $_ dayplanner.pot");
}
