#!/usr/bin/perl
# InstallLocal
# Run the day planner installer without building a package first
# Copyright (C) Eskild Hustvedt 2006
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

use strict;
use warnings;
use Cwd qw/realpath getcwd/;
use File::Basename qw/dirname/;

my $Directory = dirname(realpath($0));

unless(-e "$Directory/../../dayplanner" and -e "$Directory/../../dayplanner-daemon" and -e "$Directory/../../dayplanner-notifier") {
	die("Unable to detect the proper directory containing day planner. I should be in ./tools/installer, with day planner in ./\n");
}

$ENV{DAYPLANNER_INSTALLER_OVERRIDE_DATADIR} = "$Directory/../../";
$ENV{DAYPLANNER_CP_SILENTERRORS} = "TRUE";

print "Running tools/BuildLocale...";
if (system("$Directory/../BuildLocale &>/dev/null")) {
	print "failed - not that harmful. Continuing...\n";
} else {
	print "done\n";
}
print "Starting installer:\n";
if(defined($ARGV[0])) {
	system("$Directory/StartInstaller $ARGV[0]");
} else {
	system("$Directory/StartInstaller");
}
