#!/usr/bin/perl
# InstallLocal
# Run the Day Planner installer without building a package first
# Copyright (C) Eskild Hustvedt 2006
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;
use Cwd qw/realpath getcwd/;
use File::Basename qw/dirname/;

my $Directory = dirname(realpath($0));

unless(-e "$Directory/../../dayplanner" and -e "$Directory/../../dayplanner-daemon" and -e "$Directory/../../dayplanner-notifier") {
	die("Unable to detect the proper directory containing Day Planner. I should be in ./devel-tools/installer, with Day Planner in ./\n");
}

$ENV{DAYPLANNER_INSTALLER_OVERRIDE_DATADIR} = realpath("$Directory/../../");
$ENV{DAYPLANNER_CP_SILENTERRORS} = "TRUE";

print "Running devel-tools/BuildLocale...";
if (system("$Directory/../BuildLocale &>/dev/null")) {
	print "failed - not that harmful. Continuing...\n";
} else {
	print "done\n";
}
print "Running devel-tools/GenDesktop...";
system("$Directory/../GenDesktop DAYPLANNER_INST_DIR DAYPLANNER_INST_DIR/art &>/dev/null");
print "done\n";
print "Starting installer:\n";

chdir($Directory);

exec("$Directory/StartInstaller", @ARGV);
