#!/bin/bash
# StartInstaller
# First part of the Day Planner installer
# Copyright (C) Eskild Hustvedt 2006
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

echo -n "Preparing..."

# --- BEGIN XMSG ---
# NOTE: This is a heavily stripped version of xmsg. Get the one from the
# gfsbashlib CVS instead if you plan to use it.

# (xmsg-src/funcs)
# The function called when displaying a internal xmsg error
xmsg_int_error ()
{
	echo 1>&2 "*** xmsg ($GFBL_XMSG_VERSION): error: $*"
	if [ "$GFBL_XMSG_EXIT_ON_ERROR" == "1" ]; then exit 1;fi
}
# The function called when displaying a internal xmsg warning
xmsg_int_warning ()
{
	echo 1>&2 "*** xmsg ($GFBL_XMSG_VERSION): warning: $*"
	if [ "$GFBL_XMSG_EXIT_ON_WARNING" == "1" ]; then exit 1;fi
}
# (xmsg-src/init)
# Initialize xmsg, doesn't take any parameters.
#
# Return values:
# 0  = success
# 30 = Unable to detect any supported program (xmsg unusable)
# 31 = No DISPLAY variable set
xmsg_init ()
{
	# This is a simple function that sets which abilities xmsg has
	xmsg_setfunc ()
	{
		# This one can't be selected, if this is run we set it to 1
		export GFBL_XMSG_AVAIL=1

		export GFBL_XMSG_FSEL="$1"	# File and directory selection
		export GFBL_XMSG_LESS="$2"	# Display a file on screen
		export GFBL_XMSG_MENU="$3"	# Graphical menu
		export GFBL_XMSG_OK="$4"	# Ok dialog
		export GFBL_XMSG_QUESTION="$5"	# Question dialog
		export GFBL_XMSG_GETINPUT="$6"	# Input dialog
	}
	# First we unset variables that shouldn't be set
	unset GFBL_XMSG_PROG GFBL_XMSG_AVAIL
	# Set version variables
	export GFBL_XMSG_VERSION="0.1"

	# Initial test if we are under X
	if [ "$DISPLAY" == "" ]; then
		xmsg_int_error "X is not running, xmsg can not be used in console-only mode"
		return 31
	fi

	# Now detect which program to use
	# Only allow kdialog as primary when we are _in_ KDE.
	# Using it as default in a non-KDE environment is way too slow
	# but still a useful fallback.
	if [[ -n "$KDE_FULL_SESSION" ]]; then
		local XPROGS="$XMSG_PREFERRED_PROG kdialog zenity Xdialog  gxmessage gmessage xmessage"
	else
		local XPROGS="$XMSG_PREFERRED_PROG zenity Xdialog kdialog gxmessage gmessage xmessage"
	fi
	for a in $XPROGS; do
		if type $a &>/dev/null; then
			export GFBL_XMSG_PROG="$a"
			break
		elif [ -x $a ]; then
			export GFBL_XMSG_PROG="$a"
			break
		fi
	done
	if [ "$GFBL_XMSG_PROG" == "" ]; then
		xmsg_int_error "Unable to detect any supported program."
		export GFBL_XMSG_AVAIL=0
		return 30
	fi
	export GFBL_XMSG_BASEPROG="`basename $GFBL_XMSG_PROG`"
	# Now we need to know which functionalities we have
	case $GFBL_XMSG_BASEPROG in
		zenity ) xmsg_setfunc 1 1 1 1 1 1;;
		Xdialog ) xmsg_setfunc 1 1 1 1 1 1;;
		kdialog ) xmsg_setfunc 1 1 1 1 1 1;;
		gxmessage ) xmsg_setfunc 0 0 0 1 1 1;;
		gmessage | xmessage ) xmsg_setfunc 0 0 0 1 1;;
		* ) # Uh oh, we didn't recognise the XMSG_PREFERRED_PROG selected, ignore it and
		# restart $FUNCNAME with it unset
		xmsg_int_warning "Could not recognise the program set in XMSG_PREFERRED_PROG ($XMSG_PREFERRED_PROG), ignoring."
		unset XMSG_PREFERRED_PROG
		unset XGFBL_XMSG_BASEPROG
		$FUNCNAME
		return $?;;
	esac
	return 0
}
# (xmsg-src/ok)
# Display a "ok" box with the text supplied to xmsg_ok, ex:
# xmsg_ok "Bla bla bla bla"
#
# Returns 0 on success
# Returns 2 when no DISPLAY variable is st
# Returns 3 on no suitable program detected
xmsg_ok ()
{
	if [ "$GFBL_XMSG_AVAIL" != "1" ] || [ "$GFBL_XMSG_OK" != "1" ]; then  xmsg_int_warning "$FUNCNAME called but not available" ;return 40 ;fi
	MESSAGE="$*"
	if [ "$MESSAGE" == "" ]; then MESSAGE="Error: No message supplied to $FUNCNAME (GFSBashLib).
This is a bug in the program you are using,
please report it to the author.";xmsg_int_warning "$FUNCNAME did not get any message supplied";fi
	case $GFBL_XMSG_BASEPROG in
		gxmessage|xmessage|gmessage ) $GFBL_XMSG_PROG "$MESSAGE";;
		Xdialog ) $GFBL_XMSG_PROG --wrap --msgbox "$MESSAGE" 0 0;;
		kdialog ) $GFBL_XMSG_PROG --msgbox "$MESSAGE" 0 0 2>/dev/null;;
		zenity ) $GFBL_XMSG_PROG --info --text "$MESSAGE";;
	esac
}
# ---  END XMSG  ---

ARGS="$1"

DEFAULT_DATADIR="./dayplanner-data/"
DATADIR="$DEFAULT_DATADIR"

# Echo and display the error supplied
SI_Error () {
	echo "$@"
	[ "$ARGS" != "auto" ] && xmsg_ok "$@"
	exit 1
}

if [ "$ARGS" != "auto" ]; then
	if [ "$DISPLAY" == "" ]; then
		echo ""
		echo "The environment variable DISPLAY isn't set. This means that you don't have X running."
		echo ""
		echo "If you want to use this installer without X supply the commandline option \"auto\""
		echo "(this will install Day Planner without prompting you)"
		exit 1
	fi

	echo -n "."
	xmsg_init
fi

echo -n "."

if ! type perl &>/dev/null; then
	SI_Error "You don't have perl installed. Please install perl then re-start this installer"
fi

echo -n "."

if ! perl -e 'use Gtk2; exit(0);' &>/dev/null; then
	SI_Error "You don't have perl-Gtk2 installed. Please install it then re-start this installer"
fi

echo -n "."

if ! perl -e 'use File::Copy; use File::Path; use POSIX;exit(0);' &>/dev/null; then
	SI_Error "You appear to be missing a base perl module (one of File::Copy, File::Path or POSIX). Please check your installation of perl"
fi

echo -n "."

if [ "$DAYPLANNER_INSTALLER_OVERRIDE_DATADIR" != "" ]; then
	if [ -d "$DAYPLANNER_INSTALLER_OVERRIDE_DATADIR" ]; then
		DATADIR="$DAYPLANNER_INSTALLER_OVERRIDE_DATADIR"
	else
		echo "Error: the directory in the environment variable DAYPLANNER_INSTALLER_OVERRIDE_DATADIR does not exist. Using default: $DEFAULT_DATADIR"
	fi
fi

echo -n "."

echo "done"

if [ "`which perl`" != "/usr/bin/perl" ]; then
	RealPerl="`which perl`"
	echo "Nonstandard perl installation detected. Perl is at $RealPerl"
	echo -n "Repairing core Day Planner files..."
	for file in ./MainInstallerPart ./dayplanner-data/dayplanner ./dayplanner-data/dayplanner-notifier ./dayplanner-data/dayplanner-daemon; do
		echo -n "."
		perl -pi -e "s#/usr/bin/perl#$RealPerl#g" $file
	done
	echo "done"
fi

echo "Okay, handing control over to the perl installer part"
if ! perl ./MainInstallerPart "$DATADIR" "$@"; then
	SI_Error "An unkown error occurred with the main installer. Unable to proceed. This is a bug, please report it to the Day Planner developers."
fi
