#!/bin/bash
# StartInstaller
# First part of the Day Planner installer
# Copyright (C) Eskild Hustvedt 2006
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

echo -n "Preparing..."
# Display a "ok" box with the text supplied to xmsg_ok, ex:
# xmsg_ok "Bla bla bla bla"
#
# Returns 0 on success
# Returns 2 when no DISPLAY variable is set
# Returns 3 on no suitable program detected
xmsg_ok ()
{
	# kmessage is extremely slow when not under KDE
	if [[ -n "$KDE_FULL_SESSION" ]]; then
		local XPROGS="$XMSG_PREFERRED_PROG kdialog zenity Xdialog  gxmessage gmessage xmessage"
	else
		local XPROGS="$XMSG_PREFERRED_PROG zenity Xdialog kdialog gxmessage gmessage xmessage"
	fi
	for prog in $XPROGS;do
		if type $prog &>/dev/null; then
			GFBL_XMSG_PROG="$prog"
			GFBL_XMSG_BASEPROG="$prog"
			break;
		fi
	done
	MESSAGE="$*"
	if [ "$MESSAGE" == "" ]; then MESSAGE="Error: No message supplied to $FUNCNAME (GFSBashLib).
This is a bug in the program you are using,
please report it to the author.";fi
	if [ "$GFBL_XMSG_BASEPROG" == "" ]; then
		echo "Did not find any program to display an x message with, so dumping info here:"
		echo ""
		echo "$MESSAGE"
		return
	fi
	case $GFBL_XMSG_BASEPROG in
		gxmessage|xmessage|gmessage ) $GFBL_XMSG_PROG "$MESSAGE";;
		Xdialog ) $GFBL_XMSG_PROG --wrap --msgbox "$MESSAGE" 0 0;;
		kdialog ) $GFBL_XMSG_PROG --msgbox "$MESSAGE" 0 0 2>/dev/null;;
		zenity ) $GFBL_XMSG_PROG --info --text "$MESSAGE";;
	esac
}

ARGS="$1"

DEFAULT_DATADIR="./dayplanner-data/"
DATADIR="$DEFAULT_DATADIR"

# Echo and display the error supplied
SI_Error () {
	echo "$@"
	[ "$ARGS" != "auto" ] && xmsg_ok "$@"
	exit 1
}

if [ "$ARGS" != "auto" ]; then
	if [ "$DISPLAY" == "" ]; then
		echo ""
		echo "The environment variable DISPLAY isn't set. This means that you don't have X running."
		echo ""
		echo "If you want to use this installer without X supply the commandline option \"auto\""
		echo "(this will install Day Planner without prompting you)"
		exit 1
	fi

	echo -n "."
fi

echo -n "."

if ! type perl &>/dev/null; then
	SI_Error "You don't have perl installed. Please install perl then re-start this installer"
fi

echo -n "."

if ! perl -e 'use Gtk2; exit(0);' &>/dev/null; then
	SI_Error "You don't have perl-Gtk2 installed. Please install it then re-start this installer"
fi

echo -n "."

if ! perl -e 'use File::Copy; use File::Path; use POSIX;exit(0);' &>/dev/null; then
	SI_Error "You appear to be missing a base perl module (one of File::Copy, File::Path or POSIX). Please check your installation of perl"
fi

echo -n "."

if [ "$DAYPLANNER_INSTALLER_OVERRIDE_DATADIR" != "" ]; then
	if [ -d "$DAYPLANNER_INSTALLER_OVERRIDE_DATADIR" ]; then
		DATADIR="$DAYPLANNER_INSTALLER_OVERRIDE_DATADIR"
	else
		echo "Error: the directory in the environment variable DAYPLANNER_INSTALLER_OVERRIDE_DATADIR does not exist. Using default: $DEFAULT_DATADIR"
	fi
fi

echo -n "."

echo "done"

if [ "`which perl`" != "/usr/bin/perl" ]; then
	RealPerl="`which perl`"
	echo "Nonstandard perl installation detected. Perl is at $RealPerl"
	echo -n "Repairing core Day Planner files..."
	for file in ./MainInstallerPart ./dayplanner-data/dayplanner ./dayplanner-data/dayplanner-notifier ./dayplanner-data/dayplanner-daemon; do
		echo -n "."
		perl -pi -e "s#/usr/bin/perl#$RealPerl#g" $file
	done
	echo "done"
fi

echo "Okay, handing control over to the main installer"
if ! perl ./MainInstallerPart "$DATADIR" "$@"; then
	SI_Error "An unkown error occurred with the main installer. Unable to proceed. This is a bug, please report it to the Day Planner developers."
fi
